server:
  port: 8002

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 12345678
      url: jdbc:mysql:///oauth2?useSSL=false
      max-active: 10
      min-idle: 2
      max-wait: 6000
  jpa:
    show-sql: true

  main:
    allow-bean-definition-overriding: true