server:
  port: 8001

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 12345678
      url: jdbc:mysql:///oauth2?useSSL=false
      max-active: 10
      min-idle: 2
      max-wait: 6000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: com.oauth2.server.config.MySQLDialect
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-wait: 1000